// get all CATEGORIES
export const CATEGORIES_FETCH_REQUEST = 'CATEGORIES_FETCH_REQUEST'
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS'
export const CATEGORIES_FETCH_FAIL = 'CATEGORIES_FETCH_FAIL'

// get CATEGORIES by search
export const CATEGORIES_SEARCH_FETCH_REQUEST = 'CATEGORIES_SEARCH_FETCH_REQUEST'
export const CATEGORIES_SEARCH_FETCH_SUCCESS = 'CATEGORIES_SEARCH_FETCH_SUCCESS'
export const CATEGORIES_SEARCH_FETCH_FAIL = 'CATEGORIES_SEARCH_FETCH_FAIL'
