// get all products
export const PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST'
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS'
export const PRODUCTS_FETCH_FAIL = 'PRODUCTS_FETCH_FAIL'

// get products by search
export const PRODUCTS_SEARCH_FETCH_REQUEST = 'PRODUCTS_SEARCH_FETCH_REQUEST'
export const PRODUCTS_SEARCH_FETCH_SUCCESS = 'PRODUCTS_SEARCH_FETCH_SUCCESS'
export const PRODUCTS_SEARCH_FETCH_FAIL = 'PRODUCTS_SEARCH_FETCH_FAIL'

// get products by id
export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'
