// get all shipping
export const SHIPPING_FETCH_REQUEST = 'SHIPPING_FETCH_REQUEST'
export const SHIPPING_FETCH_SUCCESS = 'SHIPPING_FETCH_SUCCESS'
export const SHIPPING_FETCH_FAIL = 'SHIPPING_FETCH_FAIL'
